### ISSUE TITLE
Float equality (tracking issue)

### ISSUE THREAD

**Issue by ethanpailes** [ethanpailes/remake#21]
Unlike in rust, floating point numbers in remake will definitely support equality. For rust not supporting equality is the right choice because rust is a The Right Thing language, but remake is a Worse is Better language. To unpack that a little, I don't expect remake scripts to ever get much longer than a 100 lines or so (and that would be an extreme example), and having to spend time figuring out the right thing to do to compare floats is an extra burden on users. That said, it seems like there might be some issues when it comes to large values with the |f1 - f2| < epsilon approach that I’ve currently added. This is a tracking issue to remind us to revisit float comparison at some point before 1.0.

**Comment by tekknolagi** [comment]
Why do you need floating-point numbers?

**Comment by ethanpailes** [comment]
My guess is that it won't come up for 99% of users, but I want remake to be an unsupprising basic scripting language and I thought that not supporting floats would be more supprizing than supporting them. Its also not much extra work over and above supporting ints.

**Comment by ethanpailes** [comment]
closed in favor of #31
