### ISSUE TITLE
Add support for python-style typecasting

### ISSUE THREAD

**Issue by ethanpailes** [ethanpailes/remake#22]
Some things which ought to be true:

    int(5.0) == 5
    regex("hello") == /hello/
    float(5) == 5.0

**Comment by tekknolagi** [comment]
Why? Are you planning on having a static or dynamic type system? How will you handle errors?

**Comment by ethanpailes** [comment]
Definitly dynamic. I think a static type system would be overkill for a language where I expect the average program to be on the order of 3 to 5 lines.

Rightnow type errors are checked at runtime and just spit out a "TypeError: expected <foo> saw <bar>" type of thing. (That's not the exact wording, which I copied from python on the theory that python had decent ergonomics).

**Comment by ethanpailes** [comment]
Type errors are usually generated with the [`type_error` macro](https://github.com/ethanpailes/remake/blob/master/src/exec.rs#L49), which you can find scattered through the `exec.rs` file.

**Comment by ethanpailes** [comment]
closed in favor of #31
