### ISSUE TITLE
How to concatinate strings?

### ISSUE THREAD

**Issue by ethanpailes** [ethanpailes/remake#23]
I'm playing around with the operator to use for string concatination. The two operators in play are the composition operator (`.`) and the addition operator (`+`). I've currently defined concatination for the composition operator and I'm thinking of doing so for addition as well. I'm pretty torn between providing just one way to do things and following a more Worse Is Better philosophy where remake just gets out of users way (defining it on both). Another thing is that if we do just use one operator, I think plus is probably the right one because it is less supprizing.

@tekknolagi and @tchebb, thoughts?

**Comment by tekknolagi** [comment]
Let's just use `.` and leave `+` for numbers

**Comment by ethanpailes** [comment]
Additional point in favor of `.`: I just wrote the parser for plus and I couldn't figure out an obvious way to parse `+` as both an infix and postfix operator, so I made a `<+>` operator for infix plus, which is super gross.

I'll tear the string concat on `<+>` out of the patch I'm almost finished with.
